site_name: Proyecto Grand Order
site_url: https://proyectograndorder.es/
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: O-Isaac/docs

extra_css:
  - assets/styles/extra.css
  
theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo.svg
  language: es
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  plugins:
    - optimize

nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md

plugins:
  - search
  - blog
  - offline

extra:
  scope: /
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/github
      link: https://github.com/o-isaac/docs
      name: Github