site_name: Proyecto Grand Order
site_url: https://proyectograndorder.es/docs
repo_url: https://github.com/rayshift/translatefgo
repo_name: rayshift/translatefgo

extra_css:
  - https://cdn.jsdelivr.net/npm/@egjs/flicking@4.12.0/dist/flicking.min.css
  - overrides/assets/stylesheets/extra.css
  - overrides/assets/stylesheets/blog.css
  - overrides/assets/stylesheets/hero.css
  - overrides/assets/stylesheets/animations.css

extra_javascript:
  - path: overrides/assets/javascript/extra.js
    type: module
  - path: overrides/assets/javascript/carousel.js
    type: module

theme:
  name: material
  custom_dir: docs/overrides
  logo: overrides/assets/images/logo.svg
  favicon: overrides/assets/images/favicon.png
  language: es
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - blog
  - offline
  - awesome-nav
  - glightbox
  
extra:
  scope: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/o-isaac/docs
      name: Github

markdown_extensions:
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
