site_name: Proyecto Grand Order
site_url: https://proyectograndorder.es/docs
repo_url: https://github.com/rayshift/translatefgo
repo_name: rayshift/translatefgo

extra_css:
  - assets/styles/extra.css
  - assets/styles/blog.css
  - assets/styles/hero.css
  - assets/styles/animations.css
  
theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
  language: es
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - blog
  - offline
  - awesome-nav
  - glightbox
  
extra:
  scope: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/o-isaac/docs
      name: Github

markdown_extensions:
  - extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
