authors:
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  o-isaac:
    name: O-Isaac
    description: Developer
    avatar: https://github.com/o-isaac.png