name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Identify Github User
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      run: pip install mkdocs mkdocs-material
    - name: Build documentation
      run: mkdocs build --clean --site-dir dist
    - name: Pull latest gh-page
      run: git pull origin gh-pages --rebase
    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy